import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers"; // <-- 1. IMPORTE O NOVO COMPONENTE

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Providers>
          {" "}
          {/* <-- 2. ENVOLVA OS CHILDREN COM O PROVIDERS */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
